version: '3.8'

services:
  renault-detector:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Serviço opcional para treinamento
  training:
    build: .
    command: python run_pipeline.py --action full
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - CUDA_VISIBLE_DEVICES=0
    profiles:
      - training
    depends_on:
      - renault-detector

  # Serviço para desenvolvimento
  dev:
    build: .
    command: python scripts/deploy_api.py --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8001:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
    profiles:
      - dev
